/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module cu_6 (
    input [31:0] instruction,
    input [31:0] z,
    output reg [1:0] pcSel,
    output reg [5:0] alufn,
    output reg waSel,
    output reg regWE,
    output reg [4:0] regR2ASel,
    output reg [1:0] regW1DSel,
    output reg bSel,
    output reg ramWE
  );
  
  
  
  reg [5:0] opcode;
  
  reg [1:0] beqPc;
  
  always @* begin
    opcode = instruction >> 5'h1a;
    if (opcode == 6'h1d) begin
      if (z == 1'h0) begin
        beqPc = 2'h0;
      end else begin
        beqPc = 2'h1;
      end
    end
    if (opcode == 6'h1e) begin
      if (z == 1'h0) begin
        beqPc = 2'h1;
      end else begin
        beqPc = 2'h0;
      end
    end
    
    case (opcode)
      6'h18: begin
        pcSel = 2'h0;
        alufn = 6'h00;
        waSel = 1'h0;
        regWE = 1'h1;
        regR2ASel = 1'h0;
        regW1DSel = 2'h3;
        bSel = 1'h1;
        ramWE = 1'h0;
      end
      6'h19: begin
        pcSel = 2'h0;
        alufn = 6'h00;
        waSel = 1'h0;
        regWE = 1'h0;
        regR2ASel = 1'h1;
        regW1DSel = 2'h0;
        bSel = 1'h1;
        ramWE = 1'h1;
      end
      6'h1d: begin
        pcSel = beqPc;
        alufn = 6'h33;
        waSel = 1'h0;
        regWE = 1'h1;
        regR2ASel = 1'h0;
        regW1DSel = 2'h0;
        bSel = 1'h0;
        ramWE = 1'h0;
      end
      6'h1e: begin
        pcSel = beqPc;
        alufn = 6'h33;
        waSel = 1'h0;
        regWE = 1'h1;
        regR2ASel = 1'h0;
        regW1DSel = 2'h0;
        bSel = 1'h0;
        ramWE = 1'h0;
      end
      6'h20: begin
        pcSel = 2'h0;
        alufn = 6'h00;
        waSel = 1'h0;
        regWE = 1'h1;
        regR2ASel = 1'h0;
        regW1DSel = 2'h1;
        bSel = 1'h0;
        ramWE = 1'h0;
      end
      6'h21: begin
        pcSel = 2'h0;
        alufn = 6'h01;
        waSel = 1'h0;
        regWE = 1'h1;
        regR2ASel = 1'h0;
        regW1DSel = 2'h1;
        bSel = 1'h0;
        ramWE = 1'h0;
      end
      6'h23: begin
        pcSel = 2'h0;
        alufn = 6'h05;
        waSel = 1'h0;
        regWE = 1'h1;
        regR2ASel = 1'h0;
        regW1DSel = 2'h1;
        bSel = 1'h0;
        ramWE = 1'h0;
      end
      6'h25: begin
        pcSel = 2'h0;
        alufn = 6'h35;
        waSel = 1'h0;
        regWE = 1'h1;
        regR2ASel = 1'h0;
        regW1DSel = 2'h1;
        bSel = 1'h0;
        ramWE = 1'h0;
      end
      6'h28: begin
        pcSel = 2'h0;
        alufn = 6'h18;
        waSel = 1'h0;
        regWE = 1'h1;
        regR2ASel = 1'h0;
        regW1DSel = 2'h1;
        bSel = 1'h0;
        ramWE = 1'h0;
      end
      6'h2c: begin
        pcSel = 2'h0;
        alufn = 6'h20;
        waSel = 1'h0;
        regWE = 1'h1;
        regR2ASel = 1'h0;
        regW1DSel = 2'h1;
        bSel = 1'h0;
        ramWE = 1'h0;
      end
      6'h2d: begin
        pcSel = 2'h0;
        alufn = 6'h21;
        waSel = 1'h0;
        regWE = 1'h1;
        regR2ASel = 1'h0;
        regW1DSel = 2'h1;
        bSel = 1'h0;
        ramWE = 1'h0;
      end
      6'h30: begin
        pcSel = 2'h0;
        alufn = 6'h00;
        waSel = 1'h0;
        regWE = 1'h1;
        regR2ASel = 1'h0;
        regW1DSel = 2'h1;
        bSel = 1'h1;
        ramWE = 1'h0;
      end
      6'h31: begin
        pcSel = 2'h0;
        alufn = 6'h01;
        waSel = 1'h0;
        regWE = 1'h1;
        regR2ASel = 1'h0;
        regW1DSel = 2'h1;
        bSel = 1'h1;
        ramWE = 1'h0;
      end
      6'h33: begin
        pcSel = 2'h0;
        alufn = 6'h05;
        waSel = 1'h0;
        regWE = 1'h1;
        regR2ASel = 1'h0;
        regW1DSel = 2'h1;
        bSel = 1'h1;
        ramWE = 1'h0;
      end
      6'h35: begin
        pcSel = 2'h0;
        alufn = 6'h35;
        waSel = 1'h0;
        regWE = 1'h1;
        regR2ASel = 1'h0;
        regW1DSel = 2'h1;
        bSel = 1'h1;
        ramWE = 1'h0;
      end
      6'h38: begin
        pcSel = 2'h0;
        alufn = 6'h18;
        waSel = 1'h0;
        regWE = 1'h1;
        regR2ASel = 1'h0;
        regW1DSel = 2'h1;
        bSel = 1'h1;
        ramWE = 1'h0;
      end
      6'h3c: begin
        pcSel = 2'h0;
        alufn = 6'h20;
        waSel = 1'h0;
        regWE = 1'h1;
        regR2ASel = 1'h0;
        regW1DSel = 2'h1;
        bSel = 1'h1;
        ramWE = 1'h0;
      end
      6'h3d: begin
        pcSel = 2'h0;
        alufn = 6'h21;
        waSel = 1'h0;
        regWE = 1'h1;
        regR2ASel = 1'h0;
        regW1DSel = 2'h1;
        bSel = 1'h1;
        ramWE = 1'h0;
      end
      default: begin
        pcSel = 2'h2;
        alufn = 6'h00;
        waSel = 1'h0;
        regWE = 1'h1;
        regR2ASel = 1'h0;
        regW1DSel = 2'h0;
        bSel = 1'h0;
        ramWE = 1'h0;
      end
    endcase
  end
endmodule
