/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module pc_4 (
    input clk,
    input rst,
    output reg [31:0] pcC,
    output reg [31:0] pcN1,
    input [1:0] pcSel,
    input [31:0] br,
    output reg [7:0] obs
  );
  
  
  
  reg [31:0] M_pcCDff_d, M_pcCDff_q = 1'h0;
  
  reg [31:0] pcN;
  
  always @* begin
    M_pcCDff_d = M_pcCDff_q;
    
    obs = 1'h0;
    pcC = M_pcCDff_q;
    pcN = M_pcCDff_q + 1'h1;
    pcN1 = pcN;
    
    case (pcSel)
      2'h0: begin
        M_pcCDff_d = pcN;
      end
      2'h1: begin
        M_pcCDff_d = br;
        obs = 8'h42;
      end
      2'h2: begin
        M_pcCDff_d = 4'h8;
        obs = 8'h81;
      end
      2'h3: begin
        M_pcCDff_d = 3'h4;
      end
      default: begin
        M_pcCDff_d = M_pcCDff_q;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_pcCDff_q <= 1'h0;
    end else begin
      M_pcCDff_q <= M_pcCDff_d;
    end
  end
  
endmodule
