/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module rom_5 (
    input [31:0] address,
    output reg [31:0] instruction
  );
  
  
  
  integer i;
  
  reg [1151:0] data;
  
  always @* begin
    for (i = 1'h0; i < 36; i = i + 1) begin
      data[(i)*32+31-:32] = 1'h0;
    end
    data[0+31-:32] = 32'hc21f0001;
    data[32+31-:32] = 32'hc2bf000a;
    data[64+31-:32] = 32'hc01f0000;
    data[96+31-:32] = 32'hc29f0000;
    data[128+31-:32] = 32'hc0000001;
    data[160+31-:32] = 32'h97320000;
    data[192+31-:32] = 32'h77590004;
    data[224+31-:32] = 32'hf5080001;
    data[256+31-:32] = 32'he1280001;
    data[288+31-:32] = 32'hc6700001;
    data[320+31-:32] = 32'h77530017;
    data[352+31-:32] = 32'hf6100001;
    data[384+31-:32] = 32'ha1498000;
    data[416+31-:32] = 32'h7b4a0016;
    data[448+31-:32] = 32'hc2310001;
    data[480+31-:32] = 32'hc25f0070;
    data[512+31-:32] = 32'h8e528800;
    data[544+31-:32] = 32'hc252000f;
    data[576+31-:32] = 32'h7748001a;
    data[608+31-:32] = 32'h7755001c;
    data[640+31-:32] = 32'hc6b50001;
    data[672+31-:32] = 32'h775f0002;
    data[704+31-:32] = 32'h775f0016;
    data[736+31-:32] = 32'h7754000c;
    data[768+31-:32] = 32'hf2100001;
    data[800+31-:32] = 32'h775f000c;
    data[832+31-:32] = 32'hc11f0080;
    data[864+31-:32] = 32'h775f0015;
    data[896+31-:32] = 32'hf4280006;
    data[928+31-:32] = 32'h7741001f;
    data[960+31-:32] = 32'h775f0015;
    data[992+31-:32] = 32'hc1080080;
    data[1024+31-:32] = 32'hc2b0000b;
    data[1056+31-:32] = 32'h775f0015;
    instruction = data[(address)*32+31-:32];
  end
endmodule
